### ISSUE TITLE
Performance Safari macOS

### ISSUE THREAD

**Issue by S-n-d** [yitengjun/ukiyo-js#32] opened 2023-05-28 09:16 UTC
Hi, great library!

But performance is very jittery on the latest Safari (16.4) on macOS (13.3.1). Images are jumping and scrolling is very jittery. Anyone else able to reproduce this? Other browsers are perfectly fine!

**Comment by tomaszbujnowicz** [comment] 2023-06-06 16:11
The same here, it a bit jumpy on Safari iOS.

**Comment by lechatlisse** [comment] 2023-06-19 06:16
Hi there, yes me too experiencing glitches on Safari iOS latest version: as the image comes into the viewport it resizes within its container creating a flashing / glitching effect as you scroll. This is visible on your demo page as well as my site. Are you guys able to look into this please? Thanks in advance!

**Comment by yitengjun** [comment] 2023-06-20 13:21
Thank you all for your reports!

Regarding the issue occurring on Safari macOS, I believe it is likely caused by the smooth scroll library called Lenis. It appears that there is interference between the parallax scroll and smooth scroll for some unknown reason. I have not yet identified the exact cause. I believe discontinuing the use of Lenis will resolve this issue. As a temporary solution for the current demo page, I have applied the style `pointer-events: none` to the parallax elements to prevent interference with smooth scrolling.

I will continue to investigate this issue as well as the one occurring on Safari iOS.

**Comment by lechatlisse** [comment] 2023-06-20 17:19
Thank you for the quick response! FWIW I'm not having issues on macOS, but am clearly seeing a bug on iOS. I have Lenis on my site and you have it on your demo page, so it might be linked too. Here is a video playing at 50% speed of the bug on iOS, you can clearly see the image resizing as it enters viewport: https://vimeo.com/838012835/8c73b69206

**Comment by yitengjun** [comment] 2023-06-22 15:18
@lechatlisse Thank you for sharing the video! I really appreciate it, and I'll take it as a reference while addressing this issue. Another possible cause could be that this library has a specific handling for Safari, so that might be a contributing factor as well. In any case, I'll make sure to work on resolving this bug as soon as possible.

**Comment by yitengjun** [comment] 2023-06-24 12:17
@lechatlisse Fixed this issue in version [4.0.9](https://github.com/yitengjun/ukiyo-js/releases/tag/v4.0.9). Thank you for reporting it!

> FWIW I'm not having issues on macOS, but am clearly seeing a bug on iOS. I have Lenis on my site and you have it on your demo page, so it might be linked too. Here is a video playing at 50% speed of the bug on iOS, you can clearly see the image resizing as it enters viewport: https://vimeo.com/838012835/8c73b69206

**Closed by yitengjun** 2023-06-24 12:17 UTC
Labels: bug

**Comment by lechatlisse** [comment] 2023-06-25 07:36
Amazing, thanks :-)
