### ISSUE TITLE
is it really safari compatible? Loom inside

### ISSUE THREAD

**Issue by nicmare** [yitengjun/ukiyo-js#17] opened 2022-10-13 14:52 UTC
i really fell in love with ukiyo but i am not sure if it is 100% compatible with iOS. when i run the demo in safari, the images are jumping sometimes. I don't know why. Here is a screen capture of it: https://www.loom.com/share/05d0dc9d94944ab4b51e8a8297dd6b81
any thoughts?

**Comment by yitengjun** [comment] 2022-11-09 07:37
Hi @nicmare  thank you for your feedback.
This problem could possibly be caused by the address bar in safari. It is possible that each time the address bar is shown or hidden, the height of the viewport is shifted and the position of the image is also shifted.
We are currently working on a fix for this issue, so please be patient.

**Comment by yitengjun** [comment] 2022-12-30 16:16
@nicmare Sorry for the delay! 
Version 4.0.0 improved the performance of Safari on iOS. Further improvements will be made. 🙂 #18

**Closed by yitengjun** 2022-12-30 16:16 UTC
